---
language: java
os: linux
dist: xenial

jdk:
  - openjdk8

script: "mvn install"

before_deploy:
  - "zip -r tracks.zip tracks/*"

jobs:
  include:
    - stage: compile
      name: "Maven"
      script: "cd client ; ant compile"
    - name: "Server"
      script: "cd server ; ant compile"
    - name: "Editor"
      script: "cd editor ; ant compile"
    - stage: release
      deploy:
        provider: releases
        api_key: $GitHub_Token
        file:
          - "server/target/server-1.0.jar"
          - "client/target/client-1.0.jar"
          - "editor/target/editor-1.0.jar"
          - "tracks.zip"
        skip_cleanup: true
        on:
          tags: true
